# Makefile for the focaltech touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_FT3658U) += focaltech_ts.o

focaltech_ts-y += focaltech_core.o
focaltech_ts-y += focaltech_ex_fun.o
focaltech_ts-y += focaltech_ex_mode.o
focaltech_ts-y += focaltech_gesture.o
focaltech_ts-y += focaltech_esdcheck.o
focaltech_ts-y += focaltech_point_report_check.o
focaltech_ts-y += focaltech_flash.o
focaltech_ts-y += focaltech_flash/focaltech_upgrade_ft3518.o
focaltech_ts-y += focaltech_i2c.o
